const database = {
    cattleTypes: [
        {
            id: 1,
            breed: "American Angus"
        },
        {
            id: 2,
            breed: "Brown Swiss"
        },
        {
            id: 3,
            breed: "Ankina"
        },
        {
            id: 4,
            breed: "Ankole-Watusi"
        }
    ],
    drovers: [{
        "id": 1,
        "first_name": "Wanda",
        "last_name": "Ascraft",
        "gender": "Female"
    }, {
        "id": 2,
        "first_name": "Teddie",
        "last_name": "Clutten",
        "gender": "Female"
    }, {
        "id": 3,
        "first_name": "Frederich",
        "last_name": "Cubitt",
        "gender": "Male"
    }, {
        "id": 4,
        "first_name": "Belle",
        "last_name": "Saffran",
        "gender": "Female"
    }, {
        "id": 5,
        "first_name": "Shaine",
        "last_name": "Velten",
        "gender": "Female"
    }, {
        "id": 6,
        "first_name": "Wilton",
        "last_name": "Jindra",
        "gender": "Male"
    }, {
        "id": 7,
        "first_name": "Riva",
        "last_name": "Braffington",
        "gender": "Female"
    }, {
        "id": 8,
        "first_name": "Bradley",
        "last_name": "Chapling",
        "gender": "Male"
    }, {
        "id": 9,
        "first_name": "Yancy",
        "last_name": "Gresley",
        "gender": "Male"
    }, {
        "id": 10,
        "first_name": "Drud",
        "last_name": "Staig",
        "gender": "Male"
    }, {
        "id": 11,
        "first_name": "Lebbie",
        "last_name": "Bromwich",
        "gender": "Female"
    }, {
        "id": 12,
        "first_name": "Elsa",
        "last_name": "Carpmile",
        "gender": "Female"
    }, {
        "id": 13,
        "first_name": "Pen",
        "last_name": "Crebott",
        "gender": "Female"
    }, {
        "id": 14,
        "first_name": "Darcie",
        "last_name": "Sherbrook",
        "gender": "Female"
    }, {
        "id": 15,
        "first_name": "Harlan",
        "last_name": "Revie",
        "gender": "Male"
    }, {
        "id": 16,
        "first_name": "Kincaid",
        "last_name": "Stealfox",
        "gender": "Male"
    }, {
        "id": 17,
        "first_name": "Leonanie",
        "last_name": "Smeed",
        "gender": "Female"
    }, {
        "id": 18,
        "first_name": "Alphonse",
        "last_name": "Lambshine",
        "gender": "Male"
    }, {
        "id": 19,
        "first_name": "Emmy",
        "last_name": "O'Lehane",
        "gender": "Female"
    }, {
        "id": 20,
        "first_name": "Harold",
        "last_name": "Gotcher",
        "gender": "Male"
    }, {
        "id": 21,
        "first_name": "Willabella",
        "last_name": "Attarge",
        "gender": "Female"
    }, {
        "id": 22,
        "first_name": "Ynes",
        "last_name": "Gyenes",
        "gender": "Female"
    }, {
        "id": 23,
        "first_name": "Shayne",
        "last_name": "Menure",
        "gender": "Female"
    }, {
        "id": 24,
        "first_name": "Lukas",
        "last_name": "Zukerman",
        "gender": "Male"
    }, {
        "id": 25,
        "first_name": "Jacquelynn",
        "last_name": "Maloney",
        "gender": "Female"
    }, {
        "id": 26,
        "first_name": "Janina",
        "last_name": "Eisikowitch",
        "gender": "Female"
    }, {
        "id": 27,
        "first_name": "Berton",
        "last_name": "Cellier",
        "gender": "Male"
    }, {
        "id": 28,
        "first_name": "Kenny",
        "last_name": "McGenis",
        "gender": "Male"
    }, {
        "id": 29,
        "first_name": "Bink",
        "last_name": "Presman",
        "gender": "Male"
    }, {
        "id": 30,
        "first_name": "Marcello",
        "last_name": "Menichillo",
        "gender": "Male"
    }, {
        "id": 31,
        "first_name": "Farlie",
        "last_name": "Spere",
        "gender": "Male"
    }, {
        "id": 32,
        "first_name": "Gaspard",
        "last_name": "Topp",
        "gender": "Male"
    }, {
        "id": 33,
        "first_name": "Gottfried",
        "last_name": "Reicherz",
        "gender": "Male"
    }, {
        "id": 34,
        "first_name": "Davita",
        "last_name": "Glanert",
        "gender": "Female"
    }, {
        "id": 35,
        "first_name": "Pinchas",
        "last_name": "Bleacher",
        "gender": "Genderqueer"
    }, {
        "id": 36,
        "first_name": "Bealle",
        "last_name": "Worsam",
        "gender": "Male"
    }, {
        "id": 37,
        "first_name": "Annabella",
        "last_name": "Edworthie",
        "gender": "Female"
    }, {
        "id": 38,
        "first_name": "Karlyn",
        "last_name": "Whitwell",
        "gender": "Female"
    }, {
        "id": 39,
        "first_name": "Tawnya",
        "last_name": "Greenshields",
        "gender": "Female"
    }, {
        "id": 40,
        "first_name": "Sky",
        "last_name": "Di Ruggiero",
        "gender": "Female"
    }, {
        "id": 41,
        "first_name": "Talbot",
        "last_name": "Giberd",
        "gender": "Male"
    }, {
        "id": 42,
        "first_name": "Mathilde",
        "last_name": "Brennen",
        "gender": "Female"
    }, {
        "id": 43,
        "first_name": "Keelby",
        "last_name": "Keyho",
        "gender": "Male"
    }, {
        "id": 44,
        "first_name": "Georgy",
        "last_name": "Coie",
        "gender": "Male"
    }, {
        "id": 45,
        "first_name": "Melvyn",
        "last_name": "Hethron",
        "gender": "Male"
    }, {
        "id": 46,
        "first_name": "Eward",
        "last_name": "Chiplin",
        "gender": "Male"
    }, {
        "id": 47,
        "first_name": "Christophe",
        "last_name": "Hotchkin",
        "gender": "Male"
    }, {
        "id": 48,
        "first_name": "Tabitha",
        "last_name": "Strafford",
        "gender": "Female"
    }, {
        "id": 49,
        "first_name": "Lianne",
        "last_name": "Millmore",
        "gender": "Female"
    }, {
        "id": 50,
        "first_name": "Karlen",
        "last_name": "Cuel",
        "gender": "Female"
    }]
}



module.exports = { database }